services:
  - type: web
    name: ghost-cms
    runtime: image
    image:
      url: docker.io/library/ghost:5-alpine
    plan: free
    envVars:
      - key: PORT
        value: "2368"
      - key: database__client
        value: sqlite3
      - key: database__connection__filename
        value: /tmp/content/data/ghost.db
      - key: database__useNullAsDefault
        value: "true"
      - key: url
        sync: false
